const users = [
  {
    first_name: 'Mykhailo',
    last_name: 'Loniak',
    email: 'loniakmykhail+1@gmail.com',
    role: 'employer',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Olena',
    last_name: 'Shevchenko',
    email: 'olena.shevchenko+2@gmail.com',
    role: 'job_seeker',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Ivan',
    last_name: 'Petrenko',
    email: 'ivan.petrenko+3@gmail.com',
    role: 'employer',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Natalia',
    last_name: 'Havryliuk',
    email: 'natalia.havryliuk+4@gmail.com',
    role: 'job_seeker',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Andriy',
    last_name: 'Dovzhenko',
    email: 'andriy.dovzhenko+5@gmail.com',
    role: 'employer',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Iryna',
    last_name: 'Kostenko',
    email: 'iryna.kostenko+6@gmail.com',
    role: 'job_seeker',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Oleh',
    last_name: 'Melnyk',
    email: 'oleh.melnyk+7@gmail.com',
    role: 'employer',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Svitlana',
    last_name: 'Kovalchuk',
    email: 'svitlana.kovalchuk+8@gmail.com',
    role: 'job_seeker',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Yurii',
    last_name: 'Tkachenko',
    email: 'yurii.tkachenko+9@gmail.com',
    role: 'employer',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
  {
    first_name: 'Anna',
    last_name: 'Bondarenko',
    email: 'anna.bondarenko+10@gmail.com',
    role: 'job_seeker',
    password: '$2b$10$HjB7n0gPAY.wxwWvyrNihuekiwJwq2prRWt23qfehAiVXRy3YjlZ2',
    activation_token: null,
  },
];

const employerDetails = [
  {
    user_id: 1,
    company_name: 'Tech Solutions Ltd',
    company_type: 'Software Development',
    company_location: 'Kyiv, Ukraine',
    about: 'A leading software development company specializing in custom solutions.',
    country: 'Ukraine',
    city: 'Kyiv',
    phone_number: '+380631234567',
    team_size: '50-100',
    clients: ['TechCorp', 'WebSolutions', 'Innovators Inc.'],  // Масив клієнтів
    contact_info: ['contact@techsolutions.com'],  // Масив контактної інформації
    rating: '4.8',
    avatar: 'techsolutions_logo.png',
  },
  {
    user_id: 3,
    company_name: 'Creative Studios',
    company_type: 'Design Agency',
    company_location: 'Lviv, Ukraine',
    about: 'A creative agency focusing on branding and digital design.',
    country: 'Ukraine',
    city: 'Lviv',
    phone_number: '+380671234567',
    team_size: '10-20',
    clients: ['Brandify', 'DesignLab', 'CreativeWorks'],
    contact_info: ['info@creativestudios.com'],
    rating: '4.5',
    avatar: 'creativestudios_logo.png',
  },
  {
    user_id: 5,
    company_name: 'Innovative Tech',
    company_type: 'Technology Solutions',
    company_location: 'Odesa, Ukraine',
    about: 'Innovative solutions for businesses in the tech industry.',
    country: 'Ukraine',
    city: 'Odesa',
    phone_number: '+380681234567',
    team_size: '200+',
    clients: ['InnovateNow', 'TechPartners', 'FutureTech'],
    contact_info: ['support@innovatetech.com'],
    rating: '4.9',
    avatar: 'innovativetech_logo.png',
  },
  {
    user_id: 7,
    company_name: 'Global Enterprise',
    company_type: 'Consulting Services',
    company_location: 'Kyiv, Ukraine',
    about: 'Providing top-tier consulting for global enterprises.',
    country: 'Ukraine',
    city: 'Kyiv',
    phone_number: '+380631234568',
    team_size: '500+',
    clients: ['GlobalCorp', 'MegaIndustries'],
    contact_info: ['consult@globalenterprise.com'],
    rating: '5.0',
    avatar: 'globalenterprise_logo.png',
  },
];


const contractorDetails = [
  {
    user_id: 2,
    job_category: 'Web Development, UI/UX Design',
    work_experience: '5 years in front-end and back-end development, specializing in React and Node.js.',
    portfolio: 'https://portfolio.olena.com',
    section_title: 'React Developer',
    description: 'Experienced React developer with a passion for building scalable web applications.',
    avatar: 'olena_portfolio.png',
    country: 'Ukraine',
    city: 'Kyiv',
    phone_number: '+380631234569',
  },
  {
    user_id: 4,
    job_category: 'Graphic Design, Branding',
    work_experience: '3 years in graphic design, specializing in branding for small businesses.',
    portfolio: 'https://portfolio.ivan.com',
    section_title: 'Brand Designer',
    description: 'Passionate graphic designer with a strong portfolio of branding and design work.',
    avatar: 'ivan_portfolio.png',
    country: 'Ukraine',
    city: 'Lviv',
    phone_number: '+380671234568',
  },
  {
    user_id: 6,
    job_category: 'Software Engineering, Mobile Development',
    work_experience: '4 years working with mobile apps (iOS, Android) and back-end development.',
    portfolio: 'https://portfolio.iryna.com',
    section_title: 'Mobile Developer',
    description: 'Experienced mobile developer focused on building native and cross-platform apps.',
    avatar: 'iryna_portfolio.png',
    country: 'Ukraine',
    city: 'Odesa',
    phone_number: '+380681234568',
  },
  {
    user_id: 8,
    job_category: 'Data Analysis, Machine Learning',
    work_experience: '2 years in data analysis and machine learning using Python and R.',
    portfolio: 'https://portfolio.oleh.com',
    section_title: 'Data Scientist',
    description: 'Skilled data scientist with experience in machine learning and predictive modeling.',
    avatar: 'oleh_portfolio.png',
    country: 'Ukraine',
    city: 'Kyiv',
    phone_number: '+380631234570',
  },
];

const jobs = [
  {
    company_id: 1,
    job_title: "Frontend Developer",
    location: "Madrid, Spain",
    employment_type: "Full-time",
    salary: 45000,
    short_summary: "Work with React.js and modern frontend technologies.",
    full_description: "You will be building and maintaining modern user interfaces with React.js. Experience with state management and responsive design is a must.",
    application_deadline: "via platform inbox",
    visibility: "public",
    status: "active",
  },
  {
    company_id: 3,
    job_title: "Backend Developer",
    location: "Barcelona, Spain",
    employment_type: "Full-time",
    salary: 50000,
    short_summary: "Develop APIs and server-side logic using Node.js.",
    full_description: "Join our team to create high-performing backend services and APIs. Experience with Express.js and databases is required.",
    application_deadline: "by email",
    visibility: "private",
    status: "active",
  },
  {
    company_id: 5,
    job_title: "Fullstack Developer",
    location: "Madrid, Spain",
    employment_type: "Part-time",
    salary: 35000,
    short_summary: "Build both frontend and backend applications.",
    full_description: "As a Fullstack Developer, you will work on both React.js and Node.js applications. We are looking for someone who is passionate about building end-to-end systems.",
    application_deadline: "via platform inbox",
    visibility: "internal",
    status: "active",
  },
  {
    company_id: 7,
    job_title: "Product Manager",
    location: "Seville, Spain",
    employment_type: "Full-time",
    salary: 60000,
    short_summary: "Lead the development of new products and features.",
    full_description: "The Product Manager will work closely with cross-functional teams to deliver new products. Experience with Agile methodologies is required.",
    application_deadline: "via platform inbox",
    visibility: "public",
    status: "active",
  },
  {
    company_id: 1,
    job_title: "UI/UX Designer",
    location: "Valencia, Spain",
    employment_type: "Freelance",
    salary: 30000,
    short_summary: "Design user-friendly interfaces and improve user experience.",
    full_description: "We are looking for a talented UI/UX Designer to create exceptional user interfaces. Experience with Figma and Adobe XD is a plus.",
    application_deadline: "by email",
    visibility: "internal",
    status: "active",
  },
  {
    company_id: 3,
    job_title: "DevOps Engineer",
    location: "Madrid, Spain",
    employment_type: "Full-time",
    salary: 55000,
    short_summary: "Automate and streamline our development and deployment processes.",
    full_description: "As a DevOps Engineer, you will work with cloud services like AWS and CI/CD pipelines to automate and improve our software deployment process.",
    application_deadline: "external link",
    visibility: "private",
    status: "active",
  },
  {
    company_id: 5,
    job_title: "Marketing Specialist",
    location: "Madrid, Spain",
    employment_type: "Full-time",
    salary: 40000,
    short_summary: "Develop and execute marketing strategies.",
    full_description: "We are seeking a Marketing Specialist to lead our marketing campaigns, including digital marketing and social media strategy.",
    application_deadline: "via platform inbox",
    visibility: "public",
    status: "active",
  },
  {
    company_id: 7,
    job_title: "Customer Support Representative",
    location: "Remote",
    employment_type: "Full-time",
    salary: 25000,
    short_summary: "Assist customers with inquiries and issues via chat and email.",
    full_description: "Join our support team to provide assistance to customers. Strong communication skills are required.",
    application_deadline: "via platform inbox",
    visibility: "public",
    status: "active",
  },
  {
    company_id: 1,
    job_title: "QA Engineer",
    location: "Madrid, Spain",
    employment_type: "Part-time",
    salary: 35000,
    short_summary: "Ensure the quality and functionality of software applications.",
    full_description: "The QA Engineer will test and verify our products to ensure they meet high-quality standards. Experience with automated testing tools is a plus.",
    application_deadline: "by email",
    visibility: "private",
    status: "active",
  },
  {
    company_id: 3,
    job_title: "Software Architect",
    location: "Barcelona, Spain",
    employment_type: "Full-time",
    salary: 70000,
    short_summary: "Design the structure and architecture of software systems.",
    full_description: "As a Software Architect, you will be responsible for designing and overseeing the development of complex software systems and infrastructure.",
    application_deadline: "external link",
    visibility: "internal",
    status: "active",
  },
  {
    company_id: 5,
    job_title: "Database Administrator",
    location: "Valencia, Spain",
    employment_type: "Full-time",
    salary: 50000,
    short_summary: "Manage and optimize database systems.",
    full_description: "You will manage and optimize our databases, ensuring their performance, security, and reliability.",
    application_deadline: "via platform inbox",
    visibility: "private",
    status: "active",
  },
  {
    company_id: 7,
    job_title: "Sales Manager",
    location: "Madrid, Spain",
    employment_type: "Full-time",
    salary: 45000,
    short_summary: "Oversee sales teams and drive revenue growth.",
    full_description: "We are looking for a Sales Manager to lead our sales team, develop strategies, and close deals.",
    application_deadline: "via platform inbox",
    visibility: "public",
    status: "active",
  },
  {
    company_id: 1,
    job_title: "Data Scientist",
    location: "Madrid, Spain",
    employment_type: "Freelance",
    salary: 60000,
    short_summary: "Analyze complex data and provide actionable insights.",
    full_description: "The Data Scientist will work with large data sets to uncover trends and insights that will inform business decisions.",
    application_deadline: "external link",
    visibility: "private",
    status: "active",
  },
  {
    company_id: 3,
    job_title: "Network Engineer",
    location: "Seville, Spain",
    employment_type: "Full-time",
    salary: 45000,
    short_summary: "Maintain and optimize network infrastructure.",
    full_description: "Join our team to manage and optimize the network infrastructure, ensuring reliable connectivity and security.",
    application_deadline: "via platform inbox",
    visibility: "internal",
    status: "active",
  }
];

const data = {
  users,
  employerDetails,
  contractorDetails,
  jobs,
}

module.exports = data